"""Generate FeatureEngineering_Sample.ipynb using safe string construction."""
import json, uuid

def uid(): return uuid.uuid4().hex[:8]

def code(src):
    return {"cell_type":"code","execution_count":None,"id":uid(),"metadata":{},"outputs":[],"source":src}

def md(src):
    return {"cell_type":"markdown","id":uid(),"metadata":{},"source":src}

# Helper: wrap SQL in con.execute(""" ... """) with optional pre/post Python code
def sql_cell(sql, pre="", post=""):
    src = pre + 'con.execute("""\n' + sql + '\n""")\n' + post
    return code(src)

cells = []

# ── Title ──────────────────────────────────────────────────────────────────────
cells.append(md(
    "# Feature Engineering Sample\n\n"
    "Self-contained version of `FeatureEngineering_v3.ipynb` using sample CSVs.\n"
    "Uses an in-memory DuckDB connection. Run all cells top-to-bottom."
))

# ── Setup ──────────────────────────────────────────────────────────────────────
cells.append(code(
    "import duckdb\n"
    "import pandas as pd\n"
    "import numpy as np\n"
    "from pathlib import Path\n"
    "\n"
    'con = duckdb.connect(":memory:")\n'
    'pd.set_option("display.max_columns", 250)\n'
    'pd.set_option("display.max_rows", 100)\n'
    "\n"
    'DATA_DIR = "Data"\n'
    "EFFORT_MAPPING_PATH = Path(f\"{DATA_DIR}/Activity_Score_Mapping.csv\")\n"
    'ACTIVITY_TABLE = "activity_final"\n'
    'CONTACT_TABLE  = "contact_final"\n'
    "\n"
    "# Load sample CSVs as final tables\n"
    "for tbl, csv in [\n"
    '    ("activity_final",     f"{DATA_DIR}/activity_sample.csv"),\n'
    '    ("contact_final",      f"{DATA_DIR}/contact_sample.csv"),\n'
    '    ("sdk_download_final", f"{DATA_DIR}/sdk_download_sample.csv"),\n'
    "]:\n"
    '    con.execute(f"CREATE OR REPLACE TABLE {tbl} AS SELECT * FROM read_csv_auto(\'{csv}\', header=True)")\n'
    '    n = con.execute(f"SELECT COUNT(*) FROM {tbl}").fetchone()[0]\n'
    '    print(f"  {tbl}: {n:,} rows")\n'
))

# ── 1. Validate source tables ──────────────────────────────────────────────────
cells.append(md("## 1. Validate source tables"))
cells.append(code(
    "tables    = con.execute(\"SHOW TABLES\").fetchdf()\n"
    "available = set(tables.iloc[:, 0].astype(str))\n"
    "missing   = {ACTIVITY_TABLE, CONTACT_TABLE} - available\n"
    "if missing:\n"
    "    raise ValueError(f\"Missing required table(s): {missing}\")\n"
    "\n"
    "def get_columns(tbl):\n"
    "    return set(con.execute(f\"DESCRIBE {tbl}\").fetchdf()[\"column_name\"].astype(str))\n"
    "\n"
    "activity_cols = get_columns(ACTIVITY_TABLE)\n"
    "contact_cols  = get_columns(CONTACT_TABLE)\n"
    "\n"
    "required_activity_cols = {\"dev_contact\", \"activity_date\", \"activity\"}\n"
    "required_contact_cols  = {\"developer_id\"}\n"
    "if required_activity_cols - activity_cols:\n"
    "    raise ValueError(f\"Missing activity columns: {required_activity_cols - activity_cols}\")\n"
    "if required_contact_cols - contact_cols:\n"
    "    raise ValueError(f\"Missing contact columns: {required_contact_cols - contact_cols}\")\n"
    "\n"
    "for tbl in [ACTIVITY_TABLE, CONTACT_TABLE]:\n"
    "    print(f\"\\n{tbl}\")\n"
    "    display(con.execute(f\"SELECT COUNT(*) AS rows FROM {tbl}\").fetchdf())\n"
    "    display(con.execute(f\"DESCRIBE {tbl}\").fetchdf())\n"
))

# ── 2. Load AI effort mapping ──────────────────────────────────────────────────
cells.append(md("## 2. Load AI effort mapping"))
cells.append(code(
    "if not EFFORT_MAPPING_PATH.exists():\n"
    "    raise FileNotFoundError(f\"Missing {EFFORT_MAPPING_PATH}\")\n"
    "\n"
    "raw_effort_map = pd.read_csv(EFFORT_MAPPING_PATH)\n"
    "\n"
    "def clean_text(s):\n"
    "    return (s.astype(\"string\").fillna(\"\").str.strip()\n"
    "             .str.lower().str.replace(r\"\\s+\", \" \", regex=True))\n"
    "\n"
    "effort_level_rank = {\"passive\": 0, \"low\": 1, \"moderate\": 2, \"high\": 3, \"very high\": 4}\n"
    "confidence_weight = {\"high\": 1.00, \"medium\": 0.75, \"low\": 0.50, \"\": 0.50}\n"
    "\n"
    "def score_to_effort_level(score):\n"
    "    if pd.isna(score) or score == 0: return 'passive'\n"
    "    if score <= 5:  return 'low'\n"
    "    if score <= 15: return 'moderate'\n"
    "    if score <= 35: return 'high'\n"
    "    return 'very high'\n"
    "\n"
    "effort_map = raw_effort_map.copy()\n"
    "effort_map[\"mapping_object_norm\"]         = clean_text(effort_map[\"object\"])\n"
    "effort_map[\"mapping_field_norm\"]          = clean_text(effort_map[\"field\"])\n"
    "effort_map[\"mapping_value_norm\"]          = clean_text(effort_map[\"value\"])\n"
    "effort_map[\"ai_activity_score_guideline\"] = pd.to_numeric(effort_map[\"score\"], errors=\"coerce\")\n"
    "effort_map[\"ai_effort_level\"]             = effort_map[\"ai_activity_score_guideline\"].apply(score_to_effort_level)\n"
    "effort_map[\"ai_confidence\"]               = \"high\"\n"
    "effort_map[\"ai_effort_rank\"]              = effort_map[\"ai_effort_level\"].map(effort_level_rank).fillna(np.nan)\n"
    "effort_map[\"ai_confidence_weight\"]        = effort_map[\"ai_confidence\"].map(confidence_weight).fillna(1.00)\n"
    "effort_map[\"ai_weighted_effort_rank\"]     = effort_map[\"ai_effort_rank\"] * effort_map[\"ai_confidence_weight\"]\n"
    "\n"
    "em = effort_map[[\n"
    "    \"mapping_object_norm\", \"mapping_field_norm\", \"mapping_value_norm\",\n"
    "    \"ai_effort_level\", \"ai_effort_rank\", \"ai_weighted_effort_rank\",\n"
    "    \"ai_confidence\", \"ai_confidence_weight\", \"ai_activity_score_guideline\",\n"
    "]]\n"
    "\n"
    "con.register(\"em\", em)\n"
    "con.execute(\"CREATE OR REPLACE TABLE activity_effort_mapping_ai_v2 AS SELECT * FROM em\")\n"
    "con.unregister(\"em\")\n"
    "print(\"Effort mapping loaded:\", len(em), \"rows\")\n"
    "display(con.execute(\"SELECT COUNT(*) AS rows, COUNT(DISTINCT mapping_object_norm) AS objects FROM activity_effort_mapping_ai_v2\").fetchdf())\n"
))

# ── 3. activity_base_v2 ────────────────────────────────────────────────────────
cells.append(md("## 3. Activity base and contact lookup"))
cells.append(code(
    "def activity_col_expr(col, out=None, cast=\"VARCHAR\", default=\"NULL\"):\n"
    "    out = out or col\n"
    "    if col in activity_cols:\n"
    "        return f\"CAST(a.{col} AS {cast}) AS {out}\"\n"
    "    return f\"CAST({default} AS {cast}) AS {out}\"\n"
    "\n"
    "activity_score_expr = (\n"
    "    \"LEAST(GREATEST(COALESCE(TRY_CAST(a.activity_score AS DOUBLE), 0.0), 0.0), 100.0) AS activity_score\"\n"
    "    if \"activity_score\" in activity_cols else\n"
    "    \"CAST(0.0 AS DOUBLE) AS activity_score\"\n"
    ")\n"
    "\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE activity_base_v2 AS\n"
    "SELECT\n"
    "    CAST(a.dev_contact AS VARCHAR)           AS developer_id,\n"
    "    CAST(a.activity_date AS DATE)            AS activity_date,\n"
    "    LOWER(TRIM(CAST(a.activity AS VARCHAR))) AS activity,\n"
    "    {activity_col_expr('activity_name')},\n"
    "    {activity_col_expr('activity_type')},\n"
    "    {activity_col_expr('activity_role')},\n"
    "    {activity_col_expr('activity_attendance')},\n"
    "    {activity_score_expr},\n"
    "    {activity_col_expr('filepath')},\n"
    "    {activity_col_expr('lead_source')},\n"
    "    {activity_col_expr('lead_source_details')},\n"
    "    {activity_col_expr('nvidia_campaign_id')}\n"
    "FROM {ACTIVITY_TABLE} a\n"
    "WHERE a.dev_contact IS NOT NULL\n"
    "  AND TRIM(CAST(a.dev_contact AS VARCHAR)) <> ''\n"
    "  AND a.activity_date IS NOT NULL\n"
    "\"\"\")\n"
    "display(con.execute(\"SELECT COUNT(*) AS rows, COUNT(DISTINCT developer_id) AS developers, MIN(activity_date) AS min_date, MAX(activity_date) AS max_date FROM activity_base_v2\").fetchdf())\n"
))

# ── contact_one_row_v2 ─────────────────────────────────────────────────────────
cells.append(code(
    "def contact_select_expr(col, out=None, cast=\"VARCHAR\", default=\"NULL\"):\n"
    "    out = out or col\n"
    "    if col in contact_cols:\n"
    "        return f\"CAST({col} AS {cast}) AS {out}\"\n"
    "    return f\"CAST({default} AS {cast}) AS {out}\"\n"
    "\n"
    "order_terms = []\n"
    "if \"last_modified_date\" in contact_cols: order_terms.append(\"last_modified_date DESC NULLS LAST\")\n"
    "if \"created_date\" in contact_cols:       order_terms.append(\"created_date DESC NULLS LAST\")\n"
    "order_by = \", \".join(order_terms) if order_terms else \"developer_id\"\n"
    "\n"
    "contact_fields = [\n"
    "    \"developer_id\", \"created_date\", \"first_activity_date\", \"last_activity_date\",\n"
    "    \"development_areas\", \"fields_of_interest\", \"account_id\", \"account_type\",\n"
    "    \"country\", \"region\", \"industry_segment_vertical\", \"program_application_source\",\n"
    "    \"organization_english_name\", \"normalized_account_name\", \"wwfo_category\", \"wwfo_target_list\"\n"
    "]\n"
    "sel = []\n"
    "for col in contact_fields:\n"
    "    if col == \"developer_id\":\n"
    "        sel.append(\"CAST(developer_id AS VARCHAR) AS developer_id\")\n"
    "    elif col in {\"created_date\",\"first_activity_date\",\"last_activity_date\"} and col in contact_cols:\n"
    "        sel.append(f\"CAST({col} AS DATE) AS {col}\")\n"
    "    else:\n"
    "        sel.append(contact_select_expr(col))\n"
    "\n"
    "con.execute(f\"\"\"\n"
    "CREATE OR REPLACE TABLE contact_one_row_v2 AS\n"
    "WITH ranked AS (\n"
    "    SELECT {\", \".join(sel)},\n"
    "           ROW_NUMBER() OVER (PARTITION BY CAST(developer_id AS VARCHAR) ORDER BY {order_by}) AS rn\n"
    "    FROM {CONTACT_TABLE}\n"
    "    WHERE developer_id IS NOT NULL AND TRIM(CAST(developer_id AS VARCHAR)) <> ''\n"
    ")\n"
    "SELECT * EXCLUDE (rn) FROM ranked WHERE rn = 1\n"
    "\"\"\")\n"
    "display(con.execute(\"SELECT COUNT(*) AS rows, COUNT(DISTINCT developer_id) AS developers FROM contact_one_row_v2\").fetchdf())\n"
))

# ── 4. activity_dictionary_v2 ──────────────────────────────────────────────────
cells.append(md("## 4. Activity dictionary and labeled events"))

DICT_SQL = (
    "CREATE OR REPLACE TABLE activity_dictionary_v2 AS\n"
    "WITH activities AS (\n"
    "    SELECT DISTINCT activity FROM activity_base_v2 WHERE activity IS NOT NULL\n"
    ")\n"
    "SELECT\n"
    "    activity,\n"
    "    CASE\n"
    "        WHEN activity IN ('forum contributions') THEN 'Champion'\n"
    "        WHEN activity IN ('user feedback', 'bugs filed') THEN 'Evaluate'\n"
    "        WHEN activity IN ('hosted api', 'brev', 'ngc downloads', 'devzone downloads', 'sdk downloads') THEN 'Build'\n"
    "        WHEN activity IN ('dli training', 'webinars', 'on-demand views', 'conf. sessions live') THEN 'Learn'\n"
    "        ELSE 'Discover'\n"
    "    END AS fallback_journey_signal,\n"
    "    CASE\n"
    "        WHEN activity IN ('forum contributions','hosted api','brev','ngc downloads','devzone downloads',\n"
    "                          'sdk downloads','user feedback','bugs filed') THEN 'high'\n"
    "        WHEN activity IN ('dli training','webinars','on-demand views','conf. sessions live',\n"
    "                          'conference','other events','contests') THEN 'moderate'\n"
    "        ELSE 'passive'\n"
    "    END AS fallback_effort_level,\n"
    "    CASE\n"
    "        WHEN activity IN ('forum contributions','hosted api','brev','ngc downloads','devzone downloads',\n"
    "                          'sdk downloads','user feedback','bugs filed') THEN 3.0\n"
    "        WHEN activity IN ('dli training','webinars','on-demand views','conf. sessions live',\n"
    "                          'conference','other events','contests') THEN 2.0\n"
    "        ELSE 0.0\n"
    "    END AS fallback_effort_rank,\n"
    "    CASE\n"
    "        WHEN activity IN ('ngc downloads','devzone downloads','sdk downloads') THEN 'Download'\n"
    "        WHEN activity IN ('hosted api') THEN 'Hosted API'\n"
    "        WHEN activity IN ('brev') THEN 'Cloud Workspace'\n"
    "        WHEN activity IN ('forum contributions') THEN 'Community'\n"
    "        WHEN activity IN ('dli training') THEN 'Training'\n"
    "        WHEN activity IN ('webinars','conference','other events','event registrations','conf. sessions live') THEN 'Event'\n"
    "        ELSE 'Content'\n"
    "    END AS modality\n"
    "FROM activities"
)
cells.append(sql_cell(DICT_SQL,
    post='display(con.execute("SELECT COUNT(*) AS dictionary_rows FROM activity_dictionary_v2").fetchdf())\n'))

# ── activity_labeled_v2 ────────────────────────────────────────────────────────
# Note: \\b in the string below becomes \b in the actual SQL → DuckDB word boundary
LABELED_SQL = (
    "CREATE OR REPLACE TABLE activity_labeled_v2 AS\n"
    "WITH base AS (\n"
    "    SELECT\n"
    "        a.*,\n"
    "        d.fallback_journey_signal,\n"
    "        d.fallback_effort_level,\n"
    "        d.fallback_effort_rank,\n"
    "        d.modality,\n"
    "        LOWER(TRIM(COALESCE(a.activity_type, ''))) AS activity_type_norm,\n"
    "        LOWER(TRIM(COALESCE(a.activity_attendance, ''))) AS activity_attendance_norm,\n"
    "        LOWER(TRIM(COALESCE(a.activity_role, ''))) AS activity_role_norm,\n"
    "        LOWER(TRIM(COALESCE(a.activity_name, ''))) AS activity_name_norm,\n"
    "        LOWER(TRIM(COALESCE(a.filepath, ''))) AS filepath_norm,\n"
    "        LOWER(\n"
    "            COALESCE(a.activity_name, '') || ' ' ||\n"
    "            COALESCE(a.filepath, '') || ' ' ||\n"
    "            COALESCE(a.lead_source_details, '') || ' ' ||\n"
    "            COALESCE(a.activity_type, '') || ' ' ||\n"
    "            COALESCE(a.activity_role, '') || ' ' ||\n"
    "            COALESCE(a.lead_source, '')\n"
    "        ) AS persona_activity_text\n"
    "    FROM activity_base_v2 a\n"
    "    LEFT JOIN activity_dictionary_v2 d USING (activity)\n"
    "), candidates AS (\n"
    "    SELECT b.developer_id, b.activity_date, b.activity, b.activity_name, b.activity_type,\n"
    "           b.activity_role, b.activity_attendance, b.activity_score, b.filepath,\n"
    "           b.lead_source, b.lead_source_details, b.nvidia_campaign_id,\n"
    "           b.fallback_journey_signal, b.fallback_effort_level, b.fallback_effort_rank,\n"
    "           b.modality, b.persona_activity_text,\n"
    "           m.ai_effort_level, m.ai_effort_rank, m.ai_weighted_effort_rank,\n"
    "           m.ai_confidence, m.ai_confidence_weight, m.ai_activity_score_guideline,\n"
    "           'event_or_dli_or_file_type' AS ai_effort_match_source\n"
    "    FROM base b\n"
    "    JOIN activity_effort_mapping_ai_v2 m\n"
    "      ON m.mapping_value_norm = b.activity_type_norm\n"
    "     AND m.mapping_field_norm IN ('event type','course type','file type','form type','post type','status')\n"
    "     AND (\n"
    "            (b.activity IN ('conference','other events','conf. sessions live','webinars','on-demand views')\n"
    "                AND m.mapping_object_norm IN ('dev event','dev event attendance'))\n"
    "         OR (b.activity = 'dli training' AND m.mapping_object_norm = 'dev dli attendance')\n"
    "         OR (b.activity IN ('devzone downloads','ngc downloads','sdk downloads') AND m.mapping_object_norm = 'dev file')\n"
    "         OR (b.activity IN ('program applications','dev program membership') AND m.mapping_object_norm = 'dev program applications')\n"
    "         OR (b.activity IN ('user feedback','event registrations') AND m.mapping_object_norm = 'dev form')\n"
    "         OR (b.activity = 'forum contributions' AND m.mapping_object_norm = 'dev forum activities')\n"
    "     )\n"
    "    UNION ALL\n"
    "    SELECT b.developer_id, b.activity_date, b.activity, b.activity_name, b.activity_type,\n"
    "           b.activity_role, b.activity_attendance, b.activity_score, b.filepath,\n"
    "           b.lead_source, b.lead_source_details, b.nvidia_campaign_id,\n"
    "           b.fallback_journey_signal, b.fallback_effort_level, b.fallback_effort_rank,\n"
    "           b.modality, b.persona_activity_text,\n"
    "           m.ai_effort_level, m.ai_effort_rank, m.ai_weighted_effort_rank,\n"
    "           m.ai_confidence, m.ai_confidence_weight, m.ai_activity_score_guideline,\n"
    "           'attendance_status' AS ai_effort_match_source\n"
    "    FROM base b\n"
    "    JOIN activity_effort_mapping_ai_v2 m\n"
    "      ON m.mapping_value_norm = b.activity_attendance_norm\n"
    "     AND m.mapping_object_norm IN ('dev event attendance','dev dli attendance')\n"
    "     AND m.mapping_field_norm IN ('status','course type')\n"
    "    UNION ALL\n"
    "    SELECT b.developer_id, b.activity_date, b.activity, b.activity_name, b.activity_type,\n"
    "           b.activity_role, b.activity_attendance, b.activity_score, b.filepath,\n"
    "           b.lead_source, b.lead_source_details, b.nvidia_campaign_id,\n"
    "           b.fallback_journey_signal, b.fallback_effort_level, b.fallback_effort_rank,\n"
    "           b.modality, b.persona_activity_text,\n"
    "           m.ai_effort_level, m.ai_effort_rank, m.ai_weighted_effort_rank,\n"
    "           m.ai_confidence, m.ai_confidence_weight, m.ai_activity_score_guideline,\n"
    "           'role' AS ai_effort_match_source\n"
    "    FROM base b\n"
    "    JOIN activity_effort_mapping_ai_v2 m\n"
    "      ON m.mapping_value_norm = b.activity_role_norm\n"
    "     AND m.mapping_object_norm = 'dev event attendance'\n"
    "     AND m.mapping_field_norm = 'role'\n"
    "), best_candidate AS (\n"
    "    SELECT * EXCLUDE (rn)\n"
    "    FROM (\n"
    "        SELECT *,\n"
    "            ROW_NUMBER() OVER (\n"
    "                PARTITION BY developer_id, activity_date, activity, activity_name,\n"
    "                             activity_type, activity_role, activity_attendance,\n"
    "                             filepath, lead_source, lead_source_details, nvidia_campaign_id, activity_score\n"
    "                ORDER BY ai_effort_rank DESC NULLS LAST,\n"
    "                         ai_confidence_weight DESC NULLS LAST,\n"
    "                         ai_activity_score_guideline DESC NULLS LAST\n"
    "            ) AS rn\n"
    "        FROM candidates\n"
    "    ) x WHERE rn = 1\n"
    "), enriched AS (\n"
    "    SELECT b.*,\n"
    "           bc.ai_effort_level, bc.ai_effort_rank, bc.ai_weighted_effort_rank,\n"
    "           bc.ai_confidence, bc.ai_confidence_weight,\n"
    "           bc.ai_activity_score_guideline, bc.ai_effort_match_source\n"
    "    FROM base b\n"
    "    LEFT JOIN best_candidate bc\n"
    "      ON COALESCE(b.developer_id,'')        = COALESCE(bc.developer_id,'')\n"
    "     AND COALESCE(CAST(b.activity_date AS VARCHAR),'') = COALESCE(CAST(bc.activity_date AS VARCHAR),'')\n"
    "     AND COALESCE(b.activity,'')            = COALESCE(bc.activity,'')\n"
    "     AND COALESCE(b.activity_name,'')       = COALESCE(bc.activity_name,'')\n"
    "     AND COALESCE(b.activity_type,'')       = COALESCE(bc.activity_type,'')\n"
    "     AND COALESCE(b.activity_role,'')       = COALESCE(bc.activity_role,'')\n"
    "     AND COALESCE(b.activity_attendance,'') = COALESCE(bc.activity_attendance,'')\n"
    "     AND COALESCE(b.filepath,'')            = COALESCE(bc.filepath,'')\n"
    "     AND COALESCE(b.lead_source,'')         = COALESCE(bc.lead_source,'')\n"
    "     AND COALESCE(b.lead_source_details,'') = COALESCE(bc.lead_source_details,'')\n"
    "     AND COALESCE(b.nvidia_campaign_id,'')  = COALESCE(bc.nvidia_campaign_id,'')\n"
    "     AND COALESCE(b.activity_score,-999999) = COALESCE(bc.activity_score,-999999)\n"
    "), finalized AS (\n"
    "    SELECT\n"
    "        * EXCLUDE (fallback_journey_signal, fallback_effort_level, fallback_effort_rank,\n"
    "                   activity_type_norm, activity_attendance_norm, activity_role_norm,\n"
    "                   activity_name_norm, filepath_norm),\n"
    "        CASE\n"
    "            WHEN activity = 'devzone downloads' THEN\n"
    "                CASE\n"
    "                    WHEN filepath_norm LIKE '%.exe' OR filepath_norm LIKE '%installer%'\n"
    "                      OR filepath_norm LIKE '%toolkit%' OR filepath_norm LIKE '%.deb'\n"
    "                      OR filepath_norm LIKE '%.rpm' THEN 'Build'\n"
    "                    WHEN filepath_norm LIKE '%.pdf' OR filepath_norm LIKE '%docs/%'\n"
    "                      OR filepath_norm LIKE '%documentation%' THEN 'Discover'\n"
    "                    ELSE 'Evaluate'\n"
    "                END\n"
    "            WHEN LOWER(COALESCE(ai_effort_level,'')) = 'very high' THEN 'Champion'\n"
    "            ELSE fallback_journey_signal\n"
    "        END AS journey_signal,\n"
    "        COALESCE(ai_effort_level, fallback_effort_level) AS effort_level,\n"
    "        COALESCE(ai_effort_rank, fallback_effort_rank, 0.0) AS effort_rank,\n"
    "        COALESCE(ai_weighted_effort_rank, fallback_effort_rank, 0.0) AS confidence_weighted_effort_rank,\n"
    "        CASE WHEN COALESCE(ai_confidence,'') IN ('low','medium') THEN 1 ELSE 0 END AS low_medium_confidence_effort_flag,\n"
    "        CASE WHEN ABS(COALESCE(activity_score,0)-(COALESCE(ai_effort_rank,fallback_effort_rank,0.0)*25.0))>=50 THEN 1 ELSE 0 END AS score_effort_misalignment_flag,\n"
    "        COALESCE(activity_score,0)-(COALESCE(ai_effort_rank,fallback_effort_rank,0.0)*25.0) AS score_effort_gap,\n"
    "        COALESCE(activity_score,0)*COALESCE(ai_weighted_effort_rank,fallback_effort_rank,0.0) AS effort_x_activity_score\n"
    "    FROM enriched\n"
    "), scored AS (\n"
    "    SELECT *,\n"
    "        CASE WHEN REGEXP_MATCHES(persona_activity_text,'cuda|cudnn|rapids|nccl|cutlass|\\\\bdali\\\\b|gpu|accelerated|hpc') THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END AS cuda_activity_score,\n"
    "        CASE WHEN REGEXP_MATCHES(persona_activity_text,'triton|tensorrt|nemo|\\\\bnim\\\\b|llm|large language|genai|generative|inference|model') THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END AS genai_activity_score,\n"
    "        CASE WHEN REGEXP_MATCHES(persona_activity_text,'isaac|robot|ros|autonomous machine|jetson|edge ai|autonomous') THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END AS robotics_activity_score,\n"
    "        CASE WHEN REGEXP_MATCHES(persona_activity_text,'omniverse|simulation|digital twin|modulus|render|rtx|graphics') THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END AS simulation_activity_score,\n"
    "        CASE WHEN REGEXP_MATCHES(persona_activity_text,'dli|training|course|workshop|webinar|certification|learn|community') THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END AS learning_community_activity_score\n"
    "    FROM finalized\n"
    ")\n"
    "SELECT *,\n"
    "    CASE\n"
    "        WHEN GREATEST(cuda_activity_score,genai_activity_score,robotics_activity_score,\n"
    "                      simulation_activity_score,learning_community_activity_score)=0 THEN 'Other'\n"
    "        WHEN cuda_activity_score>=GREATEST(genai_activity_score,robotics_activity_score,\n"
    "                                           simulation_activity_score,learning_community_activity_score) THEN 'CUDA'\n"
    "        WHEN genai_activity_score>=GREATEST(cuda_activity_score,robotics_activity_score,\n"
    "                                            simulation_activity_score,learning_community_activity_score) THEN 'GenAI'\n"
    "        WHEN robotics_activity_score>=GREATEST(cuda_activity_score,genai_activity_score,\n"
    "                                               simulation_activity_score,learning_community_activity_score) THEN 'Robotics'\n"
    "        WHEN simulation_activity_score>=GREATEST(cuda_activity_score,genai_activity_score,\n"
    "                                                 robotics_activity_score,learning_community_activity_score) THEN 'Simulation'\n"
    "        ELSE 'Learning_Community'\n"
    "    END AS persona_hint,\n"
    "    cuda_activity_score AS cuda_persona_score,\n"
    "    genai_activity_score AS genai_persona_score,\n"
    "    robotics_activity_score AS robotics_persona_score,\n"
    "    simulation_activity_score AS simulation_persona_score,\n"
    "    learning_community_activity_score AS learning_community_persona_score\n"
    "FROM scored"
)
cells.append(sql_cell(LABELED_SQL,
    post=(
        "print('AI effort coverage')\n"
        "display(con.execute(\"SELECT COUNT(*) AS rows, SUM(CASE WHEN ai_effort_level IS NOT NULL THEN 1 ELSE 0 END) AS ai_matched, ROUND(100.0*SUM(CASE WHEN ai_effort_level IS NOT NULL THEN 1 ELSE 0 END)/COUNT(*),2) AS pct FROM activity_labeled_v2\").fetchdf())\n"
        "print('Label distribution')\n"
        "display(con.execute(\"SELECT journey_signal, effort_level, persona_hint, COUNT(*) AS rows FROM activity_labeled_v2 GROUP BY 1,2,3 ORDER BY rows DESC LIMIT 20\").fetchdf())\n"
    )))

# ── 5. developer_universe_v2 ───────────────────────────────────────────────────
cells.append(md("## 5. Developer universe and anchor date"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE developer_universe_v2 AS\n"
    "SELECT DISTINCT developer_id FROM activity_base_v2 WHERE developer_id IS NOT NULL\n"
    "UNION\n"
    "SELECT DISTINCT developer_id FROM contact_one_row_v2 WHERE developer_id IS NOT NULL",
    post=(
        "date_summary = con.execute(\"SELECT MIN(activity_date) AS min_date, MAX(activity_date) AS max_date FROM activity_labeled_v2\").fetchdf()\n"
        "ANCHOR_DATE = date_summary.loc[0, 'max_date']\n"
        "print('ANCHOR_DATE:', ANCHOR_DATE)\n"
        "display(con.execute(\"SELECT COUNT(*) AS universe_developers FROM developer_universe_v2\").fetchdf())\n"
    )
))

# ── 6. Windowed features ───────────────────────────────────────────────────────
cells.append(md("## 6. Windowed features (0–30 d, 30–90 d, 90–180 d)"))
cells.append(code(
    "WINDOWS = [('0_30d', 0, 30), ('30_90d', 30, 90), ('90_180d', 90, 180)]\n"
    "\n"
    "def build_window_features(label, start_days_ago, end_days_ago):\n"
    "    tbl = f'dev_features_{label}_v2'\n"
    "    con.execute(f\"\"\"\n"
    "    CREATE OR REPLACE TABLE {tbl} AS\n"
    "    WITH max_dt AS (SELECT MAX(activity_date) AS anchor_date FROM activity_labeled_v2),\n"
    "    agg AS (\n"
    "        SELECT\n"
    "            developer_id,\n"
    "            COUNT(*) AS activity_count,\n"
    "            SUM(activity_score) AS activity_score_sum,\n"
    "            AVG(activity_score) AS activity_score_avg,\n"
    "            COUNT(DISTINCT activity_date) AS unique_activity_days,\n"
    "            COUNT(DISTINCT activity) AS unique_activity_types,\n"
    "            COUNT(DISTINCT modality) AS unique_modalities,\n"
    "            COUNT(DISTINCT DATE_TRUNC('week', activity_date)) AS active_weeks,\n"
    "            MIN(activity_date) AS first_activity_date_window,\n"
    "            MAX(activity_date) AS last_activity_date_window,\n"
    "            SUM(CASE WHEN journey_signal='Discover'  THEN 1 ELSE 0 END) AS discover_count,\n"
    "            SUM(CASE WHEN journey_signal='Learn'     THEN 1 ELSE 0 END) AS learn_count,\n"
    "            SUM(CASE WHEN journey_signal='Evaluate'  THEN 1 ELSE 0 END) AS evaluate_count,\n"
    "            SUM(CASE WHEN journey_signal='Build'     THEN 1 ELSE 0 END) AS build_count,\n"
    "            SUM(CASE WHEN journey_signal='Champion'  THEN 1 ELSE 0 END) AS champion_count,\n"
    "            SUM(CASE WHEN effort_rank >= 3           THEN 1 ELSE 0 END) AS high_effort_count,\n"
    "            AVG(effort_rank) AS avg_effort_rank,\n"
    "            MAX(effort_rank) AS max_effort_rank,\n"
    "            SUM(confidence_weighted_effort_rank) AS total_confidence_weighted_effort,\n"
    "            AVG(score_effort_gap) AS avg_score_effort_gap,\n"
    "            SUM(score_effort_misalignment_flag) AS score_effort_misalignment_count,\n"
    "            SUM(low_medium_confidence_effort_flag) AS low_medium_confidence_effort_count,\n"
    "            SUM(effort_x_activity_score) AS effort_x_activity_score_sum,\n"
    "            SUM(CASE WHEN modality='Download'        THEN 1 ELSE 0 END) AS download_count,\n"
    "            SUM(CASE WHEN modality='Hosted API'      THEN 1 ELSE 0 END) AS hosted_api_count,\n"
    "            SUM(CASE WHEN modality='Cloud Workspace' THEN 1 ELSE 0 END) AS cloud_workspace_count,\n"
    "            SUM(CASE WHEN modality='Community'       THEN 1 ELSE 0 END) AS community_count,\n"
    "            SUM(CASE WHEN modality='Training'        THEN 1 ELSE 0 END) AS training_count,\n"
    "            SUM(CASE WHEN modality='Event'           THEN 1 ELSE 0 END) AS event_count,\n"
    "            SUM(cuda_persona_score)               AS cuda_score,\n"
    "            SUM(genai_persona_score)              AS genai_score,\n"
    "            SUM(robotics_persona_score)           AS robotics_score,\n"
    "            SUM(simulation_persona_score)         AS simulation_score,\n"
    "            SUM(learning_community_persona_score) AS learning_community_score\n"
    "        FROM activity_labeled_v2, max_dt\n"
    "        WHERE activity_date >  anchor_date - INTERVAL {end_days_ago} DAY\n"
    "          AND activity_date <= anchor_date - INTERVAL {start_days_ago} DAY\n"
    "        GROUP BY developer_id\n"
    "    )\n"
    "    SELECT\n"
    "        u.developer_id,\n"
    "        COALESCE(a.activity_count, 0)         AS activity_count,\n"
    "        COALESCE(a.activity_score_sum, 0)     AS activity_score_sum,\n"
    "        COALESCE(a.activity_score_avg, 0)     AS activity_score_avg,\n"
    "        COALESCE(a.unique_activity_days, 0)   AS unique_activity_days,\n"
    "        COALESCE(a.unique_activity_types, 0)  AS unique_activity_types,\n"
    "        COALESCE(a.unique_modalities, 0)      AS unique_modalities,\n"
    "        COALESCE(a.active_weeks, 0)           AS active_weeks,\n"
    "        a.first_activity_date_window,\n"
    "        a.last_activity_date_window,\n"
    "        CASE WHEN a.last_activity_date_window IS NULL THEN 1 ELSE 0 END AS is_missing_last_activity_window,\n"
    "        DATE_DIFF('day', a.last_activity_date_window, (SELECT anchor_date FROM max_dt)) AS days_since_last_activity_window,\n"
    "        COALESCE(a.discover_count, 0)         AS discover_count,\n"
    "        COALESCE(a.learn_count, 0)            AS learn_count,\n"
    "        COALESCE(a.evaluate_count, 0)         AS evaluate_count,\n"
    "        COALESCE(a.build_count, 0)            AS build_count,\n"
    "        COALESCE(a.champion_count, 0)         AS champion_count,\n"
    "        COALESCE(a.high_effort_count, 0)      AS high_effort_count,\n"
    "        COALESCE(a.avg_effort_rank, 0)        AS avg_effort_rank,\n"
    "        COALESCE(a.max_effort_rank, 0)        AS max_effort_rank,\n"
    "        COALESCE(a.total_confidence_weighted_effort, 0) AS total_confidence_weighted_effort,\n"
    "        COALESCE(a.avg_score_effort_gap, 0)   AS avg_score_effort_gap,\n"
    "        COALESCE(a.score_effort_misalignment_count, 0) AS score_effort_misalignment_count,\n"
    "        COALESCE(a.low_medium_confidence_effort_count, 0) AS low_medium_confidence_effort_count,\n"
    "        COALESCE(a.effort_x_activity_score_sum, 0) AS effort_x_activity_score_sum,\n"
    "        COALESCE(a.download_count, 0)         AS download_count,\n"
    "        COALESCE(a.hosted_api_count, 0)       AS hosted_api_count,\n"
    "        COALESCE(a.cloud_workspace_count, 0)  AS cloud_workspace_count,\n"
    "        COALESCE(a.community_count, 0)        AS community_count,\n"
    "        COALESCE(a.training_count, 0)         AS training_count,\n"
    "        COALESCE(a.event_count, 0)            AS event_count,\n"
    "        COALESCE(a.cuda_score, 0)             AS cuda_score,\n"
    "        COALESCE(a.genai_score, 0)            AS genai_score,\n"
    "        COALESCE(a.robotics_score, 0)         AS robotics_score,\n"
    "        COALESCE(a.simulation_score, 0)       AS simulation_score,\n"
    "        COALESCE(a.learning_community_score, 0) AS learning_community_score,\n"
    "        CASE WHEN COALESCE(a.activity_count,0)>0 THEN 1 ELSE 0 END AS has_activity,\n"
    "        LN(1+COALESCE(a.activity_count,0))    AS log_activity_count,\n"
    "        LN(1+COALESCE(a.activity_score_sum,0)) AS log_activity_score_sum,\n"
    "        LN(1+COALESCE(a.build_count,0))       AS log_build_count,\n"
    "        LN(1+COALESCE(a.high_effort_count,0)) AS log_high_effort_count,\n"
    "        COALESCE(a.activity_count,0)*1.0/NULLIF(COALESCE(a.unique_activity_days,0),0) AS activity_per_active_day,\n"
    "        COALESCE(a.build_count,0)*1.0/NULLIF(COALESCE(a.activity_count,0),0) AS build_share,\n"
    "        COALESCE(a.high_effort_count,0)*1.0/NULLIF(COALESCE(a.activity_count,0),0) AS high_effort_share\n"
    "    FROM developer_universe_v2 u\n"
    "    LEFT JOIN agg a USING (developer_id)\n"
    "    \"\"\")\n"
    "\n"
    "for label, start, end in WINDOWS:\n"
    "    build_window_features(label, start, end)\n"
    "    print(f'Built dev_features_{label}_v2')\n"
    "    display(con.execute(f'SELECT COUNT(*) AS rows, AVG(has_activity) AS pct_active FROM dev_features_{label}_v2').fetchdf())\n"
))

# ── dev_recency_features_v2 ────────────────────────────────────────────────────
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_recency_features_v2 AS\n"
    "SELECT\n"
    "    u.developer_id,\n"
    "    f0.activity_count  AS activity_count_0_30d,\n"
    "    f1.activity_count  AS activity_count_30_90d,\n"
    "    f2.activity_count  AS activity_count_90_180d,\n"
    "    f0.has_activity    AS has_activity_0_30d,\n"
    "    f1.has_activity    AS has_activity_30_90d,\n"
    "    f2.has_activity    AS has_activity_90_180d,\n"
    "    f0.log_activity_count AS log_activity_count_0_30d,\n"
    "    f1.log_activity_count AS log_activity_count_30_90d,\n"
    "    f2.log_activity_count AS log_activity_count_90_180d,\n"
    "    f0.build_count     AS build_count_0_30d,\n"
    "    f1.build_count     AS build_count_30_90d,\n"
    "    f2.build_count     AS build_count_90_180d,\n"
    "    f0.log_build_count AS log_build_count_0_30d,\n"
    "    f1.log_build_count AS log_build_count_30_90d,\n"
    "    f2.log_build_count AS log_build_count_90_180d,\n"
    "    f0.high_effort_count AS high_effort_count_0_30d,\n"
    "    f1.high_effort_count AS high_effort_count_30_90d,\n"
    "    f2.high_effort_count AS high_effort_count_90_180d,\n"
    "    f0.unique_activity_days  AS unique_activity_days_0_30d,\n"
    "    f0.unique_activity_types AS unique_activity_types_0_30d,\n"
    "    f0.unique_modalities     AS unique_modalities_0_30d,\n"
    "    f0.activity_per_active_day AS activity_per_active_day_0_30d,\n"
    "    f0.build_share             AS build_share_0_30d,\n"
    "    f0.high_effort_share       AS high_effort_share_0_30d,\n"
    "    f0.avg_effort_rank AS avg_effort_rank_0_30d,\n"
    "    f1.avg_effort_rank AS avg_effort_rank_30_90d,\n"
    "    f2.avg_effort_rank AS avg_effort_rank_90_180d,\n"
    "    f0.total_confidence_weighted_effort AS total_confidence_weighted_effort_0_30d,\n"
    "    f1.total_confidence_weighted_effort AS total_confidence_weighted_effort_30_90d,\n"
    "    f2.total_confidence_weighted_effort AS total_confidence_weighted_effort_90_180d,\n"
    "    (f0.total_confidence_weighted_effort*1.0/NULLIF(f0.activity_count,0)) AS confidence_weighted_effort_per_activity_0_30d,\n"
    "    f0.avg_score_effort_gap AS avg_score_effort_gap_0_30d,\n"
    "    f0.score_effort_misalignment_count AS score_effort_misalignment_count_0_30d,\n"
    "    (f0.score_effort_misalignment_count*1.0/NULLIF(f0.activity_count,0)) AS score_effort_misalignment_share_0_30d,\n"
    "    f0.low_medium_confidence_effort_count AS low_medium_confidence_effort_count_0_30d,\n"
    "    f0.effort_x_activity_score_sum AS effort_x_activity_score_sum_0_30d,\n"
    "    f0.days_since_last_activity_window AS days_since_last_activity_0_30d,\n"
    "    f0.is_missing_last_activity_window AS is_missing_last_activity_0_30d,\n"
    "    f0.activity_count*1.0/NULLIF(f1.activity_count,0) AS activity_velocity_0_30_vs_30_90,\n"
    "    f0.build_count   *1.0/NULLIF(f1.build_count,0)    AS build_velocity_0_30_vs_30_90,\n"
    "    (0.60*f0.activity_count+0.30*f1.activity_count+0.10*f2.activity_count) AS weighted_recent_activity,\n"
    "    (0.60*f0.build_count   +0.30*f1.build_count   +0.10*f2.build_count)    AS weighted_recent_build,\n"
    "    (0.60*f0.total_confidence_weighted_effort+0.30*f1.total_confidence_weighted_effort\n"
    "          +0.10*f2.total_confidence_weighted_effort) AS weighted_recent_confidence_effort,\n"
    "    CASE WHEN f0.activity_count>0 AND f0.build_count=0 THEN 1 ELSE 0 END AS active_non_builder_0_30d,\n"
    "    CASE WHEN f0.activity_count=0 AND f1.activity_count>0 THEN 1 ELSE 0 END AS newly_inactive_0_30d,\n"
    "    CASE WHEN f0.build_count>0 AND f0.activity_count<=2 THEN 1 ELSE 0 END AS low_volume_builder_0_30d,\n"
    "    CASE WHEN f0.high_effort_count>0 THEN 1 ELSE 0 END AS has_high_effort_0_30d,\n"
    "    CASE WHEN f0.build_count>0 OR f0.hosted_api_count>0 OR f0.cloud_workspace_count>0 THEN 1 ELSE 0 END AS recent_build_flag,\n"
    "    CASE WHEN f0.champion_count>0 THEN 1 ELSE 0 END AS recent_champion_flag\n"
    "FROM developer_universe_v2 u\n"
    "LEFT JOIN dev_features_0_30d_v2   f0 USING (developer_id)\n"
    "LEFT JOIN dev_features_30_90d_v2  f1 USING (developer_id)\n"
    "LEFT JOIN dev_features_90_180d_v2 f2 USING (developer_id)",
    post="display(con.execute(\"SELECT COUNT(*) AS rows, AVG(has_activity_0_30d) AS pct_active_0_30d FROM dev_recency_features_v2\").fetchdf())\n"
))

# ── 7. Lifetime features ───────────────────────────────────────────────────────
cells.append(md("## 7. Lifetime features"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_features_lifetime_v2 AS\n"
    "WITH agg AS (\n"
    "    SELECT\n"
    "        developer_id,\n"
    "        COUNT(*) AS lifetime_activity_count,\n"
    "        SUM(activity_score) AS lifetime_activity_score_sum,\n"
    "        AVG(activity_score) AS lifetime_activity_score_avg,\n"
    "        COUNT(DISTINCT activity_date) AS lifetime_unique_activity_days,\n"
    "        COUNT(DISTINCT activity) AS lifetime_unique_activity_types,\n"
    "        COUNT(DISTINCT modality) AS lifetime_unique_modalities,\n"
    "        COUNT(DISTINCT DATE_TRUNC('week', activity_date)) AS lifetime_active_weeks,\n"
    "        MIN(activity_date) AS lifetime_first_activity_date,\n"
    "        MAX(activity_date) AS lifetime_last_activity_date,\n"
    "        SUM(CASE WHEN journey_signal='Discover'  THEN 1 ELSE 0 END) AS lifetime_discover_count,\n"
    "        SUM(CASE WHEN journey_signal='Learn'     THEN 1 ELSE 0 END) AS lifetime_learn_count,\n"
    "        SUM(CASE WHEN journey_signal='Evaluate'  THEN 1 ELSE 0 END) AS lifetime_evaluate_count,\n"
    "        SUM(CASE WHEN journey_signal='Build'     THEN 1 ELSE 0 END) AS lifetime_build_count,\n"
    "        SUM(CASE WHEN journey_signal='Champion'  THEN 1 ELSE 0 END) AS lifetime_champion_count,\n"
    "        SUM(CASE WHEN effort_rank >= 3           THEN 1 ELSE 0 END) AS lifetime_high_effort_count,\n"
    "        AVG(effort_rank) AS lifetime_avg_effort_rank,\n"
    "        MAX(effort_rank) AS lifetime_max_effort_rank,\n"
    "        SUM(confidence_weighted_effort_rank) AS lifetime_total_confidence_weighted_effort,\n"
    "        AVG(score_effort_gap) AS lifetime_avg_score_effort_gap,\n"
    "        SUM(score_effort_misalignment_flag) AS lifetime_score_effort_misalignment_count,\n"
    "        SUM(low_medium_confidence_effort_flag) AS lifetime_low_medium_confidence_effort_count,\n"
    "        SUM(effort_x_activity_score) AS lifetime_effort_x_activity_score_sum,\n"
    "        SUM(CASE WHEN activity='dli training'        THEN 1 ELSE 0 END) AS lifetime_dli_training_count,\n"
    "        SUM(CASE WHEN activity='webinars'            THEN 1 ELSE 0 END) AS lifetime_webinar_count,\n"
    "        SUM(CASE WHEN activity='forum contributions' THEN 1 ELSE 0 END) AS lifetime_forum_count,\n"
    "        SUM(CASE WHEN activity='bugs filed'          THEN 1 ELSE 0 END) AS lifetime_bug_count,\n"
    "        SUM(CASE WHEN activity='hackathons'          THEN 1 ELSE 0 END) AS lifetime_hackathon_count,\n"
    "        SUM(CASE WHEN activity IN ('model api','hosted api') THEN 1 ELSE 0 END) AS lifetime_api_count,\n"
    "        SUM(CASE WHEN activity='devzone downloads'   THEN 1 ELSE 0 END) AS lifetime_devzone_download_count,\n"
    "        SUM(CASE WHEN activity='ngc downloads'       THEN 1 ELSE 0 END) AS lifetime_ngc_download_count,\n"
    "        SUM(cuda_persona_score)               AS cuda_score,\n"
    "        SUM(genai_persona_score)              AS genai_score,\n"
    "        SUM(robotics_persona_score)           AS robotics_score,\n"
    "        SUM(simulation_persona_score)         AS simulation_score,\n"
    "        SUM(learning_community_persona_score) AS learning_community_score,\n"
    "        SUM(CASE WHEN persona_hint='Other' THEN COALESCE(NULLIF(activity_score,0),1) ELSE 0 END) AS other_persona_score\n"
    "    FROM activity_labeled_v2 GROUP BY developer_id\n"
    "),\n"
    "filled AS (\n"
    "    SELECT\n"
    "        u.developer_id,\n"
    "        COALESCE(a.lifetime_activity_count,0) AS lifetime_activity_count,\n"
    "        COALESCE(a.lifetime_activity_score_sum,0) AS lifetime_activity_score_sum,\n"
    "        COALESCE(a.lifetime_activity_score_avg,0) AS lifetime_activity_score_avg,\n"
    "        COALESCE(a.lifetime_unique_activity_days,0) AS lifetime_unique_activity_days,\n"
    "        COALESCE(a.lifetime_unique_activity_types,0) AS lifetime_unique_activity_types,\n"
    "        COALESCE(a.lifetime_unique_modalities,0) AS lifetime_unique_modalities,\n"
    "        COALESCE(a.lifetime_active_weeks,0) AS lifetime_active_weeks,\n"
    "        a.lifetime_first_activity_date, a.lifetime_last_activity_date,\n"
    "        COALESCE(a.lifetime_discover_count,0) AS lifetime_discover_count,\n"
    "        COALESCE(a.lifetime_learn_count,0) AS lifetime_learn_count,\n"
    "        COALESCE(a.lifetime_evaluate_count,0) AS lifetime_evaluate_count,\n"
    "        COALESCE(a.lifetime_build_count,0) AS lifetime_build_count,\n"
    "        COALESCE(a.lifetime_champion_count,0) AS lifetime_champion_count,\n"
    "        COALESCE(a.lifetime_high_effort_count,0) AS lifetime_high_effort_count,\n"
    "        COALESCE(a.lifetime_avg_effort_rank,0) AS lifetime_avg_effort_rank,\n"
    "        COALESCE(a.lifetime_max_effort_rank,0) AS lifetime_max_effort_rank,\n"
    "        COALESCE(a.lifetime_total_confidence_weighted_effort,0) AS lifetime_total_confidence_weighted_effort,\n"
    "        COALESCE(a.lifetime_avg_score_effort_gap,0) AS lifetime_avg_score_effort_gap,\n"
    "        COALESCE(a.lifetime_score_effort_misalignment_count,0) AS lifetime_score_effort_misalignment_count,\n"
    "        COALESCE(a.lifetime_low_medium_confidence_effort_count,0) AS lifetime_low_medium_confidence_effort_count,\n"
    "        COALESCE(a.lifetime_effort_x_activity_score_sum,0) AS lifetime_effort_x_activity_score_sum,\n"
    "        COALESCE(a.lifetime_dli_training_count,0) AS lifetime_dli_training_count,\n"
    "        COALESCE(a.lifetime_webinar_count,0) AS lifetime_webinar_count,\n"
    "        COALESCE(a.lifetime_forum_count,0) AS lifetime_forum_count,\n"
    "        COALESCE(a.lifetime_bug_count,0) AS lifetime_bug_count,\n"
    "        COALESCE(a.lifetime_hackathon_count,0) AS lifetime_hackathon_count,\n"
    "        COALESCE(a.lifetime_api_count,0) AS lifetime_api_count,\n"
    "        COALESCE(a.lifetime_devzone_download_count,0) AS lifetime_devzone_download_count,\n"
    "        COALESCE(a.lifetime_ngc_download_count,0) AS lifetime_ngc_download_count,\n"
    "        COALESCE(a.cuda_score,0) AS cuda_score,\n"
    "        COALESCE(a.genai_score,0) AS genai_score,\n"
    "        COALESCE(a.robotics_score,0) AS robotics_score,\n"
    "        COALESCE(a.simulation_score,0) AS simulation_score,\n"
    "        COALESCE(a.learning_community_score,0) AS learning_community_score,\n"
    "        COALESCE(a.other_persona_score,0) AS other_persona_score\n"
    "    FROM developer_universe_v2 u LEFT JOIN agg a USING (developer_id)\n"
    "),\n"
    "p99 AS (\n"
    "    SELECT\n"
    "        APPROX_QUANTILE(lifetime_activity_count,0.99) AS p99_activity_count,\n"
    "        APPROX_QUANTILE(lifetime_build_count,0.99) AS p99_build_count,\n"
    "        APPROX_QUANTILE(lifetime_total_confidence_weighted_effort,0.99) AS p99_total_confidence_weighted_effort,\n"
    "        APPROX_QUANTILE(lifetime_effort_x_activity_score_sum,0.99) AS p99_effort_x_activity_score_sum,\n"
    "        APPROX_QUANTILE(lifetime_activity_score_sum,0.99) AS p99_activity_score_sum\n"
    "    FROM filled\n"
    ")\n"
    "SELECT f.*,\n"
    "    CASE\n"
    "        WHEN f.lifetime_unique_activity_days=1 THEN 'tourist'\n"
    "        WHEN f.lifetime_build_count+f.lifetime_champion_count<=2\n"
    "          AND f.lifetime_high_effort_count=0\n"
    "          AND f.lifetime_devzone_download_count>=1 THEN 'free_email_user'\n"
    "        ELSE 'real_user'\n"
    "    END AS user_type,\n"
    "    CASE\n"
    "        WHEN f.lifetime_champion_count>=1 THEN 'Champion'\n"
    "        WHEN f.lifetime_build_count>=1    THEN 'Build'\n"
    "        WHEN f.lifetime_evaluate_count>=1 THEN 'Evaluate'\n"
    "        WHEN f.lifetime_learn_count>=1    THEN 'Learn'\n"
    "        WHEN f.lifetime_discover_count>=1 THEN 'Discover'\n"
    "        ELSE 'None'\n"
    "    END AS max_stage_reached,\n"
    "    CASE WHEN lifetime_activity_count>0 THEN 1 ELSE 0 END AS has_lifetime_activity,\n"
    "    LN(1+lifetime_activity_count) AS log_lifetime_activity_count,\n"
    "    LN(1+lifetime_activity_score_sum) AS log_lifetime_activity_score_sum,\n"
    "    LN(1+lifetime_build_count) AS log_lifetime_build_count,\n"
    "    LN(1+lifetime_high_effort_count) AS log_lifetime_high_effort_count,\n"
    "    lifetime_total_confidence_weighted_effort*1.0/NULLIF(lifetime_activity_count,0) AS effort_per_activity_lifetime,\n"
    "    lifetime_score_effort_misalignment_count*1.0/NULLIF(lifetime_activity_count,0) AS score_effort_misalignment_share_lifetime,\n"
    "    LN(1+lifetime_total_confidence_weighted_effort) AS log_lifetime_total_confidence_weighted_effort,\n"
    "    LN(1+lifetime_effort_x_activity_score_sum) AS log_lifetime_effort_x_activity_score_sum,\n"
    "    LEAST(lifetime_activity_count,p99.p99_activity_count) AS clipped_lifetime_activity_count_p99,\n"
    "    LEAST(lifetime_build_count,p99.p99_build_count) AS clipped_lifetime_build_count_p99,\n"
    "    LEAST(lifetime_activity_score_sum,p99.p99_activity_score_sum) AS clipped_lifetime_activity_score_sum_p99,\n"
    "    LEAST(lifetime_total_confidence_weighted_effort,p99.p99_total_confidence_weighted_effort) AS clipped_lifetime_total_confidence_weighted_effort_p99,\n"
    "    LEAST(lifetime_effort_x_activity_score_sum,p99.p99_effort_x_activity_score_sum) AS clipped_lifetime_effort_x_activity_score_sum_p99,\n"
    "    LN(1+LEAST(lifetime_activity_count,p99.p99_activity_count)) AS log_clipped_lifetime_activity_count_p99,\n"
    "    LN(1+LEAST(lifetime_activity_score_sum,p99.p99_activity_score_sum)) AS log_clipped_lifetime_activity_score_sum_p99,\n"
    "    LN(1+LEAST(lifetime_total_confidence_weighted_effort,p99.p99_total_confidence_weighted_effort)) AS log_clipped_lifetime_total_confidence_weighted_effort_p99,\n"
    "    LN(1+LEAST(lifetime_effort_x_activity_score_sum,p99.p99_effort_x_activity_score_sum)) AS log_clipped_lifetime_effort_x_activity_score_sum_p99,\n"
    "    lifetime_activity_count*1.0/NULLIF(lifetime_active_weeks,0) AS activity_per_active_week_lifetime,\n"
    "    lifetime_build_count*1.0/NULLIF(lifetime_activity_count,0) AS build_share_lifetime,\n"
    "    lifetime_high_effort_count*1.0/NULLIF(lifetime_activity_count,0) AS high_effort_share_lifetime\n"
    "FROM filled f CROSS JOIN p99",
    post=(
        "display(con.execute(\"SELECT COUNT(*) AS rows, MAX(lifetime_activity_count) AS max_count FROM dev_features_lifetime_v2\").fetchdf())\n"
        "display(con.execute(\"SELECT user_type, COUNT(*) AS developers FROM dev_features_lifetime_v2 GROUP BY 1 ORDER BY developers DESC\").fetchdf())\n"
    )
))

# ── 8. Weekly + meaningful week + activation ───────────────────────────────────
cells.append(md("## 8. Weekly features and activation gating\n\nAdapted from `FeatureENgineering.ipynb` — source changed to `activity_labeled_v2`."))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_weekly_features_v2 AS\n"
    "WITH weekly AS (\n"
    "    SELECT\n"
    "        developer_id,\n"
    "        DATE_TRUNC('week', activity_date) AS week_start,\n"
    "        COUNT(*) AS activity_count_total,\n"
    "        SUM(activity_score) AS activity_score_sum,\n"
    "        COUNT(DISTINCT activity) AS unique_activity_types,\n"
    "        COUNT(DISTINCT modality) AS unique_modalities,\n"
    "        SUM(CASE WHEN journey_signal='Discover'  THEN 1 ELSE 0 END) AS discover_count,\n"
    "        SUM(CASE WHEN journey_signal='Learn'     THEN 1 ELSE 0 END) AS learn_count,\n"
    "        SUM(CASE WHEN journey_signal='Evaluate'  THEN 1 ELSE 0 END) AS evaluate_count,\n"
    "        SUM(CASE WHEN journey_signal='Build'     THEN 1 ELSE 0 END) AS build_count,\n"
    "        SUM(CASE WHEN journey_signal='Champion'  THEN 1 ELSE 0 END) AS champion_count,\n"
    "        SUM(CASE WHEN effort_rank >= 3           THEN 1 ELSE 0 END) AS high_effort_count,\n"
    "        SUM(CASE WHEN modality='Download'        THEN 1 ELSE 0 END) AS download_count,\n"
    "        SUM(CASE WHEN modality='Hosted API'      THEN 1 ELSE 0 END) AS hosted_api_count,\n"
    "        SUM(CASE WHEN modality='Cloud Workspace' THEN 1 ELSE 0 END) AS cloud_workspace_count,\n"
    "        SUM(CASE WHEN persona_hint='CUDA'       THEN activity_score ELSE 0 END) AS cuda_score,\n"
    "        SUM(CASE WHEN persona_hint='GenAI'      THEN activity_score ELSE 0 END) AS genai_score,\n"
    "        SUM(CASE WHEN persona_hint='Robotics'   THEN activity_score ELSE 0 END) AS robotics_score,\n"
    "        SUM(CASE WHEN persona_hint='Simulation' THEN activity_score ELSE 0 END) AS simulation_score\n"
    "    FROM activity_labeled_v2\n"
    "    GROUP BY 1, 2\n"
    ")\n"
    "SELECT *,\n"
    "    LN(1+activity_count_total) AS activity_count_log,\n"
    "    LN(1+activity_score_sum)   AS activity_score_log,\n"
    "    LN(1+build_count)          AS build_count_log,\n"
    "    LN(1+high_effort_count)    AS high_effort_count_log\n"
    "FROM weekly",
    post="display(con.execute(\"SELECT COUNT(*) AS developer_weeks, COUNT(DISTINCT developer_id) AS developers FROM dev_weekly_features_v2\").fetchdf())\n"
))

cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_meaningful_week_v2 AS\n"
    "WITH weekly AS (\n"
    "    SELECT\n"
    "        developer_id,\n"
    "        DATE_TRUNC('week', activity_date) AS week_start,\n"
    "        COUNT(DISTINCT activity_date) AS active_days,\n"
    "        SUM(CASE WHEN journey_signal='Build'    THEN 1 ELSE 0 END) AS build_count,\n"
    "        SUM(CASE WHEN journey_signal='Champion' THEN 1 ELSE 0 END) AS champion_count,\n"
    "        SUM(CASE WHEN effort_rank=2             THEN 1 ELSE 0 END) AS moderate_effort_count,\n"
    "        SUM(CASE WHEN effort_rank>=3            THEN 1 ELSE 0 END) AS high_effort_count,\n"
    "        COUNT(DISTINCT CASE\n"
    "            WHEN journey_signal IN ('Learn','Evaluate') AND effort_rank<=1 THEN activity_date\n"
    "        END) AS passive_learn_eval_days\n"
    "    FROM activity_labeled_v2\n"
    "    GROUP BY 1, 2\n"
    ")\n"
    "SELECT *,\n"
    "    CASE\n"
    "        WHEN build_count>0 OR champion_count>0 THEN 1\n"
    "        WHEN moderate_effort_count>0 OR high_effort_count>0 THEN 1\n"
    "        WHEN passive_learn_eval_days>=2 THEN 1\n"
    "        ELSE 0\n"
    "    END AS meaningful_week_flag\n"
    "FROM weekly",
    post="display(con.execute(\"SELECT SUM(meaningful_week_flag) AS meaningful_weeks, ROUND(AVG(meaningful_week_flag),3) AS rate FROM dev_meaningful_week_v2\").fetchdf())\n"
))

cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_activation_v2 AS\n"
    "WITH first_dates AS (\n"
    "    SELECT developer_id, MIN(activity_date) AS first_activity_date\n"
    "    FROM activity_labeled_v2 GROUP BY developer_id\n"
    "),\n"
    "lifetime_signals AS (\n"
    "    SELECT developer_id,\n"
    "        SUM(CASE WHEN journey_signal IN ('Build','Champion') THEN 1 ELSE 0 END) AS lifetime_build_champion_events,\n"
    "        COUNT(*) AS lifetime_activity_count_for_activation,\n"
    "        MAX(activity_date) AS lifetime_last_activity_date\n"
    "    FROM activity_labeled_v2 GROUP BY developer_id\n"
    "),\n"
    "first_90_meaningful AS (\n"
    "    SELECT f.developer_id,\n"
    "        SUM(CASE WHEN mw.meaningful_week_flag=1 THEN 1 ELSE 0 END) AS meaningful_weeks_first_90d\n"
    "    FROM first_dates f\n"
    "    LEFT JOIN dev_meaningful_week_v2 mw\n"
    "        ON f.developer_id=mw.developer_id\n"
    "       AND mw.week_start >= DATE_TRUNC('week', f.first_activity_date)\n"
    "       AND mw.week_start <  f.first_activity_date + INTERVAL 90 DAY\n"
    "    GROUP BY f.developer_id\n"
    "),\n"
    "last_meaningful AS (\n"
    "    SELECT developer_id,\n"
    "        MAX(CASE WHEN meaningful_week_flag=1 THEN week_start END) AS last_meaningful_week_start,\n"
    "        SUM(CASE WHEN meaningful_week_flag=1 THEN 1 ELSE 0 END) AS lifetime_meaningful_weeks\n"
    "    FROM dev_meaningful_week_v2 GROUP BY developer_id\n"
    ")\n"
    "SELECT\n"
    "    u.developer_id,\n"
    "    f.first_activity_date,\n"
    "    COALESCE(l.lifetime_build_champion_events,0) AS lifetime_build_champion_events,\n"
    "    COALESCE(m.meaningful_weeks_first_90d,0) AS meaningful_weeks_first_90d,\n"
    "    COALESCE(l.lifetime_activity_count_for_activation,0) AS lifetime_activity_count_for_activation,\n"
    "    l.lifetime_last_activity_date,\n"
    "    COALESCE(lm.lifetime_meaningful_weeks,0) AS lifetime_meaningful_weeks,\n"
    "    lm.last_meaningful_week_start,\n"
    "    CASE\n"
    "        WHEN COALESCE(l.lifetime_build_champion_events,0)>=1 THEN 1\n"
    "        WHEN COALESCE(m.meaningful_weeks_first_90d,0)>=2 THEN 1\n"
    "        ELSE 0\n"
    "    END AS is_activated,\n"
    "    CASE\n"
    "        WHEN COALESCE(l.lifetime_build_champion_events,0)>=1 THEN 'Build_or_Champion_Ever'\n"
    "        WHEN COALESCE(m.meaningful_weeks_first_90d,0)>=2 THEN 'Two_Meaningful_Weeks_First_90d'\n"
    "        ELSE 'Unactivated'\n"
    "    END AS activation_reason\n"
    "FROM developer_universe_v2 u\n"
    "LEFT JOIN first_dates f       USING (developer_id)\n"
    "LEFT JOIN lifetime_signals l  USING (developer_id)\n"
    "LEFT JOIN first_90_meaningful m USING (developer_id)\n"
    "LEFT JOIN last_meaningful lm  USING (developer_id)",
    post="display(con.execute(\"SELECT activation_reason, COUNT(*) AS developers FROM dev_activation_v2 GROUP BY 1 ORDER BY developers DESC\").fetchdf())\n"
))

# ── 9. Dormancy status ─────────────────────────────────────────────────────────
cells.append(md("## 9. Dormancy status"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_dormancy_status_v2 AS\n"
    "WITH max_dt AS (\n"
    "    SELECT MAX(activity_date) AS anchor_date FROM activity_labeled_v2\n"
    "),\n"
    "base AS (\n"
    "    SELECT a.*,\n"
    "        DATE_DIFF('day', lifetime_last_activity_date,\n"
    "                  (SELECT anchor_date FROM max_dt)) AS days_since_last_activity\n"
    "    FROM dev_activation_v2 a\n"
    ")\n"
    "SELECT *,\n"
    "CASE\n"
    "    WHEN lifetime_activity_count_for_activation=0 THEN 'Unactivated'\n"
    "    WHEN days_since_last_activity < 30  THEN 'Active'\n"
    "    WHEN days_since_last_activity < 90  THEN 'Cooling'\n"
    "    WHEN days_since_last_activity < 365 THEN 'At_Risk'\n"
    "    ELSE 'Dormant'\n"
    "END AS dormancy_status\n"
    "FROM base",
    post=(
        "display(con.execute(\"SELECT dormancy_status, COUNT(*) AS developers, ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),2) AS pct FROM dev_dormancy_status_v2 GROUP BY 1 ORDER BY developers DESC\").fetchdf())\n"
    )
))

# ── 10. Effort level ───────────────────────────────────────────────────────────
cells.append(md("## 10. Developer effort level"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_effort_level_v2 AS\n"
    "WITH base AS (\n"
    "    SELECT\n"
    "        lf.developer_id,\n"
    "        lf.lifetime_activity_count,\n"
    "        lf.lifetime_unique_activity_types,\n"
    "        lf.lifetime_unique_modalities,\n"
    "        lf.lifetime_high_effort_count,\n"
    "        lf.lifetime_avg_effort_rank,\n"
    "        lf.lifetime_build_count,\n"
    "        lf.log_clipped_lifetime_activity_count_p99,\n"
    "        lf.log_clipped_lifetime_activity_score_sum_p99,\n"
    "        lf.log_clipped_lifetime_total_confidence_weighted_effort_p99,\n"
    "        lf.log_clipped_lifetime_effort_x_activity_score_sum_p99,\n"
    "        COALESCE(r.activity_count_0_30d,0)  AS activity_count_0_30d,\n"
    "        COALESCE(r.activity_count_30_90d,0) AS activity_count_30_90d,\n"
    "        COALESCE(r.activity_count_90_180d,0) AS activity_count_90_180d,\n"
    "        COALESCE(r.unique_activity_types_0_30d,0) AS unique_activity_types_0_30d,\n"
    "        COALESCE(r.weighted_recent_confidence_effort,0) AS weighted_recent_confidence_effort,\n"
    "        COALESCE(r.avg_effort_rank_0_30d,0) AS avg_effort_rank_0_30d,\n"
    "        COALESCE(r.recent_build_flag,0) AS recent_build_flag,\n"
    "        CASE\n"
    "            WHEN COALESCE(r.activity_count_0_30d,0)  >0 THEN 1.00\n"
    "            WHEN COALESCE(r.activity_count_30_90d,0) >0 THEN 0.75\n"
    "            WHEN COALESCE(r.activity_count_90_180d,0)>0 THEN 0.50\n"
    "            ELSE 0.25\n"
    "        END AS recency_weight\n"
    "    FROM dev_features_lifetime_v2 lf\n"
    "    LEFT JOIN dev_recency_features_v2 r USING (developer_id)\n"
    "), scored AS (\n"
    "    SELECT *,\n"
    "        (  0.30*COALESCE(log_clipped_lifetime_total_confidence_weighted_effort_p99,0)\n"
    "         + 0.20*COALESCE(log_clipped_lifetime_effort_x_activity_score_sum_p99,0)\n"
    "         + 0.15*COALESCE(log_clipped_lifetime_activity_count_p99,0)\n"
    "         + 0.10*LN(1+COALESCE(lifetime_unique_activity_types,0))\n"
    "         + 0.10*LN(1+COALESCE(lifetime_unique_modalities,0))\n"
    "         + 0.10*LN(1+COALESCE(weighted_recent_confidence_effort,0))\n"
    "         + 0.05*COALESCE(lifetime_avg_effort_rank,0)\n"
    "        )*recency_weight AS developer_effort_score\n"
    "    FROM base\n"
    "), cutoffs AS (\n"
    "    SELECT\n"
    "        QUANTILE_CONT(developer_effort_score,0.50) AS p50_effort,\n"
    "        QUANTILE_CONT(developer_effort_score,0.75) AS p75_effort,\n"
    "        QUANTILE_CONT(developer_effort_score,0.90) AS p90_effort\n"
    "    FROM scored WHERE lifetime_activity_count>0\n"
    ")\n"
    "SELECT s.*,\n"
    "    CASE\n"
    "        WHEN s.lifetime_activity_count=0         THEN 'no activity'\n"
    "        WHEN s.developer_effort_score>=c.p90_effort THEN 'very high effort'\n"
    "        WHEN s.developer_effort_score>=c.p75_effort THEN 'high effort'\n"
    "        WHEN s.developer_effort_score>=c.p50_effort THEN 'medium effort'\n"
    "        ELSE 'low effort'\n"
    "    END AS developer_effort_level,\n"
    "    CASE\n"
    "        WHEN s.lifetime_activity_count=0         THEN 0\n"
    "        WHEN s.developer_effort_score>=c.p90_effort THEN 4\n"
    "        WHEN s.developer_effort_score>=c.p75_effort THEN 3\n"
    "        WHEN s.developer_effort_score>=c.p50_effort THEN 2\n"
    "        ELSE 1\n"
    "    END AS developer_effort_rank\n"
    "FROM scored s CROSS JOIN cutoffs c",
    post="display(con.execute(\"SELECT developer_effort_level, developer_effort_rank, COUNT(*) AS developers FROM dev_effort_level_v2 GROUP BY 1,2 ORDER BY developer_effort_rank DESC\").fetchdf())\n"
))

# ── 11. Persona ────────────────────────────────────────────────────────────────
cells.append(md("## 11. Persona"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_contact_persona_v2 AS\n"
    "WITH base AS (\n"
    "    SELECT developer_id,\n"
    "        LOWER(\n"
    "            COALESCE(development_areas,'') || ' ' ||\n"
    "            COALESCE(fields_of_interest,'') || ' ' ||\n"
    "            COALESCE(industry_segment_vertical,'')\n"
    "        ) AS profile_text\n"
    "    FROM contact_one_row_v2\n"
    ")\n"
    "SELECT developer_id,\n"
    "    CASE WHEN REGEXP_MATCHES(profile_text,'cuda|gpu|accelerated|hpc|rapids|cudnn') THEN 1.0 ELSE 0.0 END AS cuda_profile_score,\n"
    "    CASE WHEN REGEXP_MATCHES(profile_text,'genai|generative|llm|ai|machine learning|deep learning|inference') THEN 1.0 ELSE 0.0 END AS genai_profile_score,\n"
    "    CASE WHEN REGEXP_MATCHES(profile_text,'robot|isaac|ros|jetson|autonomous|edge') THEN 1.0 ELSE 0.0 END AS robotics_profile_score,\n"
    "    CASE WHEN REGEXP_MATCHES(profile_text,'simulation|omniverse|digital twin|graphics|render|rtx') THEN 1.0 ELSE 0.0 END AS simulation_profile_score,\n"
    "    CASE WHEN REGEXP_MATCHES(profile_text,'training|education|student|academic|community|developer program') THEN 1.0 ELSE 0.0 END AS learning_community_profile_score\n"
    "FROM base"
))

cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_persona_v2 AS\n"
    "WITH base AS (\n"
    "    SELECT lf.developer_id,\n"
    "        lf.cuda_score              +COALESCE(cp.cuda_profile_score,0)              AS cuda_score,\n"
    "        lf.genai_score             +COALESCE(cp.genai_profile_score,0)             AS genai_score,\n"
    "        lf.robotics_score          +COALESCE(cp.robotics_profile_score,0)          AS robotics_score,\n"
    "        lf.simulation_score        +COALESCE(cp.simulation_profile_score,0)        AS simulation_score,\n"
    "        lf.learning_community_score+COALESCE(cp.learning_community_profile_score,0) AS learning_community_score,\n"
    "        lf.other_persona_score\n"
    "    FROM dev_features_lifetime_v2 lf\n"
    "    LEFT JOIN dev_contact_persona_v2 cp USING (developer_id)\n"
    "),\n"
    "norm AS (\n"
    "    SELECT *,\n"
    "        cuda_score+genai_score+robotics_score+simulation_score+learning_community_score AS specific_persona_score,\n"
    "        cuda_score+genai_score+robotics_score+simulation_score+learning_community_score+other_persona_score AS total_persona_score\n"
    "    FROM base\n"
    "),\n"
    "shares AS (\n"
    "    SELECT *,\n"
    "        COALESCE(cuda_score/NULLIF(specific_persona_score,0),0)              AS cuda_share,\n"
    "        COALESCE(genai_score/NULLIF(specific_persona_score,0),0)             AS genai_share,\n"
    "        COALESCE(robotics_score/NULLIF(specific_persona_score,0),0)          AS robotics_share,\n"
    "        COALESCE(simulation_score/NULLIF(specific_persona_score,0),0)        AS simulation_share,\n"
    "        COALESCE(learning_community_score/NULLIF(specific_persona_score,0),0) AS learning_community_share,\n"
    "        COALESCE(other_persona_score/NULLIF(total_persona_score,0),0)        AS other_share\n"
    "    FROM norm\n"
    "),\n"
    "entropy AS (\n"
    "    SELECT *,\n"
    "        -1*(\n"
    "            CASE WHEN cuda_share>0              THEN cuda_share*LN(cuda_share)                         ELSE 0 END+\n"
    "            CASE WHEN genai_share>0             THEN genai_share*LN(genai_share)                       ELSE 0 END+\n"
    "            CASE WHEN robotics_share>0          THEN robotics_share*LN(robotics_share)                 ELSE 0 END+\n"
    "            CASE WHEN simulation_share>0        THEN simulation_share*LN(simulation_share)             ELSE 0 END+\n"
    "            CASE WHEN learning_community_share>0 THEN learning_community_share*LN(learning_community_share) ELSE 0 END\n"
    "        )/LN(5) AS persona_entropy\n"
    "    FROM shares\n"
    "),\n"
    "long_scores AS (\n"
    "    SELECT developer_id,'CUDA' AS persona,cuda_share AS score FROM entropy\n"
    "    UNION ALL SELECT developer_id,'GenAI',genai_share FROM entropy\n"
    "    UNION ALL SELECT developer_id,'Robotics',robotics_share FROM entropy\n"
    "    UNION ALL SELECT developer_id,'Simulation',simulation_share FROM entropy\n"
    "    UNION ALL SELECT developer_id,'Learning_Community',learning_community_share FROM entropy\n"
    "),\n"
    "ranked AS (\n"
    "    SELECT *,\n"
    "        ROW_NUMBER() OVER (PARTITION BY developer_id ORDER BY score DESC, persona) AS rn,\n"
    "        LEAD(score) OVER (PARTITION BY developer_id ORDER BY score DESC, persona) AS second_score\n"
    "    FROM long_scores\n"
    ")\n"
    "SELECT e.*,\n"
    "    CASE WHEN e.specific_persona_score=0 THEN 'Unknown' ELSE r.persona END AS persona,\n"
    "    CASE WHEN e.specific_persona_score=0 THEN 0          ELSE r.score  END AS persona_confidence,\n"
    "    CASE\n"
    "        WHEN e.specific_persona_score=0 THEN 'Unknown'\n"
    "        WHEN r.score>=0.70 THEN 'High'\n"
    "        WHEN r.score>=0.45 THEN 'Medium'\n"
    "        ELSE 'Low'\n"
    "    END AS persona_confidence_tier,\n"
    "    CASE\n"
    "        WHEN e.specific_persona_score=0 THEN 0\n"
    "        WHEN e.persona_entropy>=0.60 OR r.score-COALESCE(r.second_score,0)<=0.15 THEN 1\n"
    "        ELSE 0\n"
    "    END AS mixed_persona_flag\n"
    "FROM entropy e\n"
    "LEFT JOIN ranked r ON e.developer_id=r.developer_id AND r.rn=1",
    post="display(con.execute(\"SELECT persona, persona_confidence_tier, COUNT(*) AS developers FROM dev_persona_v2 GROUP BY 1,2 ORDER BY developers DESC\").fetchdf())\n"
))

# ── 12. Journey state ──────────────────────────────────────────────────────────
cells.append(md("## 12. Journey state"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_journey_state_v2 AS\n"
    "WITH base AS (\n"
    "    SELECT\n"
    "        r.developer_id,\n"
    "        COALESCE(r.activity_count_0_30d,0)  AS activity_count_0_30d,\n"
    "        COALESCE(r.activity_count_30_90d,0) AS activity_count_30_90d,\n"
    "        COALESCE(r.activity_count_90_180d,0) AS activity_count_90_180d,\n"
    "        COALESCE(r.build_count_0_30d,0)     AS build_count_0_30d,\n"
    "        COALESCE(r.build_count_30_90d,0)    AS build_count_30_90d,\n"
    "        COALESCE(r.high_effort_count_0_30d,0)  AS high_effort_count_0_30d,\n"
    "        COALESCE(r.high_effort_count_30_90d,0) AS high_effort_count_30_90d,\n"
    "        COALESCE(r.unique_activity_types_0_30d,0) AS unique_activity_types_0_30d,\n"
    "        COALESCE(r.unique_modalities_0_30d,0)     AS unique_modalities_0_30d,\n"
    "        COALESCE(r.recent_build_flag,0)    AS recent_build_flag,\n"
    "        COALESCE(r.recent_champion_flag,0) AS recent_champion_flag,\n"
    "        COALESCE(d.is_activated,0) AS is_activated,\n"
    "        COALESCE(d.lifetime_activity_count_for_activation,0) AS lifetime_activity_count_for_activation,\n"
    "        COALESCE(d.dormancy_status,'Unactivated') AS dormancy_status,\n"
    "        CASE WHEN d.dormancy_status='Dormant' THEN 1 ELSE 0 END AS dormant_flag,\n"
    "        CASE WHEN d.dormancy_status='At_Risk' THEN 1 ELSE 0 END AS at_risk_flag,\n"
    "        CASE WHEN d.dormancy_status='Cooling' THEN 1 ELSE 0 END AS cooling_flag,\n"
    "        d.days_since_last_activity,\n"
    "        COALESCE(l.lifetime_activity_count,0)        AS lifetime_activity_count,\n"
    "        COALESCE(l.lifetime_build_count,0)           AS lifetime_build_count,\n"
    "        COALESCE(l.lifetime_champion_count,0)        AS lifetime_champion_count,\n"
    "        COALESCE(l.lifetime_high_effort_count,0)     AS lifetime_high_effort_count,\n"
    "        COALESCE(l.lifetime_unique_activity_types,0) AS lifetime_unique_activity_types,\n"
    "        CASE\n"
    "            WHEN COALESCE(r.activity_count_0_30d,0)=0 AND COALESCE(r.activity_count_30_90d,0)=0 THEN NULL\n"
    "            WHEN COALESCE(r.activity_count_30_90d,0)=0 AND COALESCE(r.activity_count_0_30d,0)>0 THEN 2.0\n"
    "            ELSE CAST(r.activity_count_0_30d AS DOUBLE)/NULLIF(CAST(r.activity_count_30_90d AS DOUBLE),0)\n"
    "        END AS recent_activity_trend_ratio\n"
    "    FROM dev_recency_features_v2 r\n"
    "    LEFT JOIN dev_dormancy_status_v2 d USING (developer_id)\n"
    "    LEFT JOIN dev_features_lifetime_v2 l USING (developer_id)\n"
    "),\n"
    "scored AS (\n"
    "    SELECT *,\n"
    "        CASE\n"
    "            WHEN activity_count_0_30d>=5 THEN 'High'\n"
    "            WHEN activity_count_0_30d>=2 THEN 'Medium'\n"
    "            WHEN activity_count_0_30d=1  THEN 'Low'\n"
    "            ELSE 'None'\n"
    "        END AS activity_volume_band,\n"
    "        CASE\n"
    "            WHEN build_count_0_30d>0 OR recent_build_flag=1 OR lifetime_build_count>=5 THEN 'Build_Intent'\n"
    "            WHEN high_effort_count_0_30d>0 OR lifetime_high_effort_count>=5 THEN 'Evaluation_Intent'\n"
    "            WHEN activity_count_0_30d>0 THEN 'Learning_Intent'\n"
    "            ELSE 'No_Recent_Intent'\n"
    "        END AS intent_signal,\n"
    "        CASE\n"
    "            WHEN recent_activity_trend_ratio IS NULL THEN NULL\n"
    "            WHEN recent_activity_trend_ratio>=1.5   THEN 'Accelerating'\n"
    "            WHEN recent_activity_trend_ratio>=0.7   THEN 'Stable'\n"
    "            WHEN recent_activity_trend_ratio>0      THEN 'Declining'\n"
    "            ELSE NULL\n"
    "        END AS trend_signal\n"
    "    FROM base\n"
    "),\n"
    "behavior AS (\n"
    "    SELECT *,\n"
    "        CASE\n"
    "            WHEN lifetime_activity_count=0 THEN 'Unactivated'\n"
    "            WHEN build_count_0_30d>0 OR recent_build_flag=1 OR lifetime_build_count>=10 THEN 'Builder'\n"
    "            WHEN high_effort_count_0_30d>0 OR lifetime_high_effort_count>=10 THEN 'Evaluator'\n"
    "            WHEN activity_count_0_30d>0 AND unique_activity_types_0_30d>=2 THEN 'Explorer'\n"
    "            WHEN activity_count_0_30d>0 THEN 'Learner'\n"
    "            WHEN lifetime_activity_count>0 THEN 'Historically_Active'\n"
    "            ELSE 'Unactivated'\n"
    "        END AS behavior_journey_stage_30d\n"
    "    FROM scored\n"
    ")\n"
    "SELECT\n"
    "    developer_id,\n"
    "    behavior_journey_stage_30d,\n"
    "    CASE\n"
    "        WHEN behavior_journey_stage_30d='Unactivated' THEN 'Unactivated'\n"
    "        WHEN dormancy_status IN ('Dormant','At_Risk','Cooling')\n"
    "        THEN dormancy_status||'_'||behavior_journey_stage_30d\n"
    "        ELSE behavior_journey_stage_30d\n"
    "    END AS current_journey_state_30d,\n"
    "    CASE\n"
    "        WHEN behavior_journey_stage_30d='Unactivated'        THEN 0\n"
    "        WHEN behavior_journey_stage_30d='Historically_Active' THEN 1\n"
    "        WHEN behavior_journey_stage_30d='Learner'             THEN 2\n"
    "        WHEN behavior_journey_stage_30d='Explorer'            THEN 3\n"
    "        WHEN behavior_journey_stage_30d='Evaluator'           THEN 4\n"
    "        WHEN behavior_journey_stage_30d='Builder'             THEN 5\n"
    "        ELSE 1\n"
    "    END AS behavior_journey_rank_30d,\n"
    "    CASE\n"
    "        WHEN behavior_journey_stage_30d='Unactivated'        THEN 0\n"
    "        WHEN behavior_journey_stage_30d='Historically_Active' THEN 1\n"
    "        WHEN behavior_journey_stage_30d='Learner'             THEN 2\n"
    "        WHEN behavior_journey_stage_30d='Explorer'            THEN 3\n"
    "        WHEN behavior_journey_stage_30d='Evaluator'           THEN 4\n"
    "        WHEN behavior_journey_stage_30d='Builder'             THEN 5\n"
    "        ELSE 1\n"
    "    END AS current_journey_rank_30d,\n"
    "    activity_volume_band, intent_signal, trend_signal, recent_activity_trend_ratio\n"
    "FROM behavior",
    post=(
        "display(con.execute(\"SELECT behavior_journey_stage_30d, COUNT(*) AS developers, ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),2) AS pct FROM dev_journey_state_v2 GROUP BY 1 ORDER BY developers DESC\").fetchdf())\n"
    )
))

# ── 13. Final profile ──────────────────────────────────────────────────────────
cells.append(md("## 13. Final developer profile"))
cells.append(sql_cell(
    "CREATE OR REPLACE TABLE dev_profile_final_v4 AS\n"
    "SELECT\n"
    "    u.developer_id,\n"
    "    p.persona, p.persona_confidence, p.persona_confidence_tier,\n"
    "    p.persona_entropy, p.mixed_persona_flag,\n"
    "    p.cuda_share, p.genai_share, p.robotics_share, p.simulation_share, p.learning_community_share,\n"
    "    e.developer_effort_score, e.developer_effort_level, e.developer_effort_rank,\n"
    "    e.recency_weight AS effort_recency_weight,\n"
    "    js.behavior_journey_stage_30d, js.behavior_journey_rank_30d,\n"
    "    js.current_journey_state_30d,  js.current_journey_rank_30d,\n"
    "    COALESCE(d.is_activated,0) AS is_activated,\n"
    "    d.lifetime_meaningful_weeks,\n"
    "    d.last_meaningful_week_start,\n"
    "    DATE_DIFF('day', d.last_meaningful_week_start, CURRENT_DATE) AS days_since_last_meaningful_week,\n"
    "    d.days_since_last_activity,\n"
    "    COALESCE(d.dormancy_status,'Unactivated') AS dormancy_status,\n"
    "    CASE WHEN d.dormancy_status='Dormant' THEN 1 ELSE 0 END AS dormant_flag,\n"
    "    CASE WHEN d.dormancy_status='At_Risk' THEN 1 ELSE 0 END AS at_risk_flag,\n"
    "    CASE WHEN d.dormancy_status='Cooling' THEN 1 ELSE 0 END AS cooling_flag,\n"
    "    CASE\n"
    "        WHEN COALESCE(lf.lifetime_activity_count,0)=0 THEN 'Unactivated'\n"
    "        WHEN lf.user_type='tourist'         THEN 'Tourist'\n"
    "        WHEN lf.user_type='free_email_user' THEN 'FreeEmail'\n"
    "        WHEN COALESCE(d.days_since_last_activity,\n"
    "                      DATE_DIFF('day',d.last_meaningful_week_start,CURRENT_DATE))>=365\n"
    "             THEN 'Dormant_'||lf.max_stage_reached\n"
    "        WHEN COALESCE(d.days_since_last_activity,\n"
    "                      DATE_DIFF('day',d.last_meaningful_week_start,CURRENT_DATE))>=180\n"
    "             THEN 'AtRisk_'||lf.max_stage_reached\n"
    "        ELSE 'Active_'||lf.max_stage_reached\n"
    "    END AS final_lifecycle_status,\n"
    "    r.* EXCLUDE (developer_id),\n"
    "    lf.* EXCLUDE (developer_id,cuda_score,genai_score,robotics_score,\n"
    "                  simulation_score,learning_community_score,other_persona_score),\n"
    "    c.created_date AS contact_created_date,\n"
    "    c.first_activity_date AS contact_first_activity_date,\n"
    "    c.last_activity_date  AS contact_last_activity_date,\n"
    "    c.account_id, c.account_type, c.country, c.region,\n"
    "    c.industry_segment_vertical, c.program_application_source,\n"
    "    c.organization_english_name, c.normalized_account_name,\n"
    "    c.wwfo_category, c.wwfo_target_list,\n"
    "    CASE WHEN c.developer_id IS NULL THEN 1 ELSE 0 END AS missing_contact_metadata_flag\n"
    "FROM developer_universe_v2 u\n"
    "LEFT JOIN dev_persona_v2           p  USING (developer_id)\n"
    "LEFT JOIN dev_effort_level_v2      e  USING (developer_id)\n"
    "LEFT JOIN dev_journey_state_v2     js USING (developer_id)\n"
    "LEFT JOIN dev_dormancy_status_v2   d  USING (developer_id)\n"
    "LEFT JOIN dev_recency_features_v2  r  USING (developer_id)\n"
    "LEFT JOIN dev_features_lifetime_v2 lf USING (developer_id)\n"
    "LEFT JOIN contact_one_row_v2       c  USING (developer_id)",
    post=(
        "display(con.execute(\"SELECT COUNT(*) AS rows, COUNT(DISTINCT developer_id) AS developers, ROUND(AVG(developer_effort_score),3) AS avg_effort FROM dev_profile_final_v4\").fetchdf())\n"
        "display(con.execute(\"SELECT persona, current_journey_state_30d, dormancy_status, final_lifecycle_status, COUNT(*) AS developers FROM dev_profile_final_v4 GROUP BY 1,2,3,4 ORDER BY developers DESC LIMIT 30\").fetchdf())\n"
    )
))

# ── Final inventory ────────────────────────────────────────────────────────────
cells.append(md("## Final table inventory"))
cells.append(code(
    "final_tables = [\n"
    '    "activity_effort_mapping_ai_v2", "activity_base_v2", "contact_one_row_v2",\n'
    '    "activity_dictionary_v2", "activity_labeled_v2", "developer_universe_v2",\n'
    '    "dev_features_0_30d_v2", "dev_features_30_90d_v2", "dev_features_90_180d_v2",\n'
    '    "dev_recency_features_v2", "dev_features_lifetime_v2",\n'
    '    "dev_weekly_features_v2", "dev_meaningful_week_v2", "dev_activation_v2",\n'
    '    "dev_dormancy_status_v2", "dev_effort_level_v2",\n'
    '    "dev_contact_persona_v2", "dev_persona_v2",\n'
    '    "dev_journey_state_v2", "dev_profile_final_v4",\n'
    "]\n"
    "rows = []\n"
    "for t in final_tables:\n"
    "    exists = con.execute(\"SELECT COUNT(*) FROM information_schema.tables WHERE table_name=?\", [t]).fetchone()[0]>0\n"
    "    n = con.execute(f\"SELECT COUNT(*) FROM {t}\").fetchone()[0] if exists else None\n"
    "    rows.append({\"table\": t, \"rows\": n, \"exists\": exists})\n"
    "display(pd.DataFrame(rows))\n"
))

# ── Export dev_profile_final_v4 for FE_check ──────────────────────────────────
cells.append(md("## Export for FE_check"))
cells.append(code(
    "import os\n"
    "out_parquet = f\"{DATA_DIR}/dev_profile_sample.parquet\"\n"
    "con.execute(f\"COPY dev_profile_final_v4 TO '{out_parquet}' (FORMAT PARQUET)\")\n"
    "print(f\"Exported dev_profile_final_v4 -> {out_parquet}\")\n"
    "n = con.execute(\"SELECT COUNT(*) FROM dev_profile_final_v4\").fetchone()[0]\n"
    "print(f\"  {n:,} rows\")\n"
))

# ── Write notebook ─────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "cells": cells
}

out = "c:/Users/Owner/OneDrive/Documents/NVIDIA/Spring2026_IndustryProject/FeatureEngineering_Sample.ipynb"
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written {len(cells)} cells -> {out}")
